name: premedico
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flutter_onboarding_slider: ^1.0.11
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.3
  get: ^4.6.6
  get_storage: ^2.1.1
  change_app_package_name: ^1.1.0
  zego_uikit_prebuilt_call: ^4.9.1
  lottie: ^3.1.2
  firebase_messaging: ^14.9.2
  shimmer: ^3.0.0
  dash_chat_2: ^0.0.20
  flutter_credit_card: ^4.0.1
  google_maps_flutter: ^2.6.1
  intl: ^0.18.1
  readmore: ^3.0.0
  flutter_gemini: ^2.0.3
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
