// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5BZnjsk0oYlm_XXdczrrXXZOkzmanrQw',
    appId: '1:304622880796:web:f0b6edbd7bec58209537d9',
    messagingSenderId: '304622880796',
    projectId: 'flutterapp1-4a7a5',
    authDomain: 'flutterapp1-4a7a5.firebaseapp.com',
    storageBucket: 'flutterapp1-4a7a5.appspot.com',
    measurementId: 'G-XM03T2KYJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB90ssoMKqfbND-Iwg1t-GoLEvzKFLtLeU',
    appId: '1:304622880796:android:1a7b34a4c8fd11679537d9',
    messagingSenderId: '304622880796',
    projectId: 'flutterapp1-4a7a5',
    storageBucket: 'flutterapp1-4a7a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYDZfmy0gVQgsVBGbsmzem-hdn4_sbOJU',
    appId: '1:304622880796:ios:eb3deb22cf2a556f9537d9',
    messagingSenderId: '304622880796',
    projectId: 'flutterapp1-4a7a5',
    storageBucket: 'flutterapp1-4a7a5.appspot.com',
    iosBundleId: 'com.comma.premedico',
  );
}
