// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5BZnjsk0oYlm_XXdczrrXXZOkzmanrQw',
    appId: '1:304622880796:web:c8754b980e5dd1e69537d9',
    messagingSenderId: '304622880796',
    projectId: 'flutterapp1-4a7a5',
    authDomain: 'flutterapp1-4a7a5.firebaseapp.com',
    storageBucket: 'flutterapp1-4a7a5.appspot.com',
    measurementId: 'G-XH73DXRS2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB90ssoMKqfbND-Iwg1t-GoLEvzKFLtLeU',
    appId: '1:304622880796:android:43f5449a78f97e0f9537d9',
    messagingSenderId: '304622880796',
    projectId: 'flutterapp1-4a7a5',
    storageBucket: 'flutterapp1-4a7a5.appspot.com',
  );
}
